apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ default "wordpress-test.sfxworks.net" .Values.host }} ##TODO https
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 80