apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wp-pvc
spec:
  storageClassName: "rook-nfs-wordpress"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi