apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: {{ .Release.Name }}-wordpress
  ports:
  - protocol: TCP
    port: 80
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: {{ .Release.Name }}-mariadb
  ports:
  - protocol: TCP
    port: 3306
    name: db
