apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rook-pv-claim
spec:
  storageClassName: "rook-nfs-wordpress"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
